### ISSUE TITLE
buildHtml does not capture closure variables

### ISSUE THREAD

**Issue by hamidb80** [karaxnim/karax#231]
here I used a example provided in `readme.md` file, modified slightly:

```nim
include karax / prelude

var lines: seq[kstring] = @[] # CASE 1

proc createDom(): VNode =
  # var lines: seq[kstring] = @[] # CASE 2

  result = buildHtml(tdiv):
    button:
      text "Say hello!"
      proc onclick(ev: Event; n: VNode) =
        lines.add "Hello simulated universe"
    for x in lines:
      tdiv:
        text x

setRenderer createDom
```

note that `CASE 1` works fine, but in `CASE 2` no line is added when you click on the button [no error happens]

**Comment by geotre** [comment]
This is not an issue with closure variables, I think maybe just a slight misunderstanding of how Karax works.

Here's what is happening from Karax's point of view, when you use the code in case 2:

1. It's told that whenever something changes, it should call `createDom` to get the latest vdom tree (you tell it this with the _`setRenderer`_ call)
2. It calls `createDom` to get the initial vdom tree to render. `createDom` initializes `lines` as an empty seq, then returns a tree of _VNodes_ representing the desired state of the dom. This initial tree does not include any text from `lines`, as it is empty
3. It renders that initial tree to the page, in doing so attaches an _onclick_ handler to the button element. This handler is wrapped so that it [includes a call to _`redraw()`_](https://github.com/karaxnim/karax/blob/5498909fc565f6e32b26c3af7e3f5ad8f60b6e65/karax/karax.nim#L780)
4. You click the button, firing the _onclick_ event handler
5. The event handler adds a string to the `lines` seq, then calls `redraw()`
6. To redraw the app, Karax calls `createDom` to get the latest updated version of the vdom tree
7. `createDom` initializes `lines` as an empty seq, then returns a tree of vnodes. This tree again does not include any text from `lines`, as it is empty
8. Karax diffs the two trees, but does not find any changes as they are the same, so nothing happens

This is not a bug in Karax, so there is no error message expected
