### ISSUE TITLE
Broken functionalities when karax used with grammarly or languagetool (and possibly other extensions)

### ISSUE THREAD

**Issue by pietroppeter** [karaxnim/karax#232]
this came up in the [forum today](https://forum.nim-lang.org/t/9571#62973) and it is only reported as an issue in nimforum (https://github.com/nim-lang/nimforum/issues/303), but it is probably better also to have it here, since it is an issue to be fixed in karax.

In short:
- extensions like grammarly or languagetool modify the dom and can corrupt nodes owned by karax
- karax implemented functionalities fail as a result

we do still miss:
- an understanding on how other virtual dom frameworks handle this case

we could probably benefit from:
- a smaller reproducible example (other than working dircetly with nimforum)

also, what is the "knete" approach that @Araq was referring to in the linked nimforum issue?

**Comment by geotre** [comment]
Normally the dom looks like this:

![image](https://user-images.githubusercontent.com/1889120/200043332-0ba95768-90d0-4ea7-ac63-93011ca6018c.png)


The extension inserts elements alongside the textarea:

![image](https://user-images.githubusercontent.com/1889120/200042798-4d09c74b-78b4-4a5f-865b-e21e76ab554b.png)

Causing exception

![image](https://user-images.githubusercontent.com/1889120/200042892-a6ed380c-cd77-4658-a8fc-9e419528486d.png)


The exception is triggered by one of the `doAssert same(...)` calls (e.g. [1](https://github.com/karaxnim/karax/blob/6abcb77e2180a1bbc34525b1e0ac07fc67d5ff2e/karax/karax.nim#L605), [2](https://github.com/karaxnim/karax/blob/6abcb77e2180a1bbc34525b1e0ac07fc67d5ff2e/karax/karax.nim#L617), [3](https://github.com/karaxnim/karax/blob/6abcb77e2180a1bbc34525b1e0ac07fc67d5ff2e/karax/karax.nim#L668)). I'm not sure which it is exactly because the forum is compiled with an older copy of Karax.

**Comment by geotre** [comment]
Can reproduce the issue with something like this:

```nim
import std/dom
include pkg/karax/prelude

var val: cstring

proc draw: VNode =
  buildHtml(tdiv):
    textarea:
      proc onkeyup (ev: Event, n: VNode) =
        val = n.value
    p: text val

setRenderer draw, clientPostRenderCallback=proc =
  document.getElementById("ROOT").appendChild(document.createElement("p"))
```

Basically anything that adds elements as a descendant of the Karax root node

**Comment by Araq** [comment]
Well you can diactivate the assertions and see if it works out...

**Comment by geotre** [comment]
@pietroppeter this should be fixed now, do you want to test and close the issue?

**Comment by pietroppeter** [comment]
hi, well, I was not suffering from that bug, I opened the issue to give visibility to this problem (and apparently it worked! ;)). People that are known to me to suffer from this issue are @tsoj (opened the original issue), and, as I learned today from discord, also @ringabout. Others that could help test this out?

**Comment by ringabout** [comment]
It can be closed; ref https://github.com/nim-lang/nimforum/pull/335

**Comment by pietroppeter** [comment]
thanks!
